name: Ellen Gummesson
description: Random ramblings, overall geekiness and other musings
url: http://ellengummesson.com/
exclude: [Rakefile, README.md, global.css]
markdown: kramdown
permalink: blog/:year/:month/:day/:title
tag_dir: blog/tag
paginate: 5
paginate_path: blog/page/:num
post:
  template: _post.txt
  extension: md
editor: gvim
transfer:
  robocopy: _site\ D:\Git\gummesson.github.com\ /e
  rsync: -av _site/ ~/Git/gummesson.github.com/
