name: Ellen Gummesson
description: Random ramblings, musings and geekiness
url: http://ellengummesson.com/
exclude: [Rakefile, README.md, config.rb, sass]
markdown: kramdown
permalink: blog/:year/:month/:day/:title
tag_dir: blog/tag
paginate: 5
paginate_path: blog/page/:num
